workflows:
  humai_react_native:
    name: HumAI Digital Twin - React Native
    max_build_duration: 60

    environment:
      node: 18
      # ovdje kasnije možeš dodati npr. ENV varijable

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install dependencies
        script: |
          if [ -f yarn.lock ]; then
            yarn install
          else
            npm install
          fi

      - name: Run tests
        script: |
          if [ -f yarn.lock ]; then
            yarn test || echo "No tests yet"
          else
            npm test || echo "No tests yet"
          fi

      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk